version: '3'

services:
  mkdocs:
    image: "aisuhua/mkdocs:${VERSION:-latest}"
    build:
      context: .
      args:
        VERSION: "${VERSION:-latest}"
    ports:
      - 8000:8000
    volumes: 
      - .:/docs

  mkdocs-webhook:
    image: "aisuhua/mkdocs:${VERSION:-latest}-webhook"
    build:
      context: .
      dockerfile: webhook.Dockerfile
      args:
        VERSION: "${VERSION:-latest}"
    environment:
      - REPO_URL=http://197.197.0.11:3000/sysadmin/docker-mkdocs.git
    ports:
      - 9000:9000 
