version: '3'

services:
  mkdocs:
    image: "aisuhua/mkdocs-material:${VERSION:-latest}"
    build:
      context: .
      args:
        VERSION: "${VERSION:-latest}"
    ports:
      - 8000:8000
    volumes: 
      - .:/docs
