site_name: 我的文档
site_url: http://localhost:8000
site_author: aisuhua
site_description: >-
  Just writing

repo_name: aisuhua/docker-mkdocs
repo_url: https://github.com/aisuhua/docker-mkdocs.git
edit_uri: edit/master/docs

theme:
  name: material
  use_directory_urls: true
  language: zh
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - announce.dismiss
    - content.action.edit
    #- content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - primary: black
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font: false
  icon:
    repo: fontawesome/brands/git-alt

plugins:
  - search:
      lang: zh
      separator: '[\s\u200b\-]'
  - minify:
      minify_html: true
  - git-committers:
  - git-authors:
      show_contribution: true
      show_email_address: false
  - git-revision-date-localized:
      enable_creation_date: true
  - blog:
      blog_toc: false

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          percent_encode: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.magiclink

extra_css:
  - assets/stylesheets/font.css
  - assets/stylesheets/style.css
